In [248]:
#imports
import sys
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from mpl_toolkits.mplot3d import Axes3D


In [249]:
# Constants
Gravitational_Constant=6.6743*(10**-11)
dt=1.0
total_time=5.0
time=0.0

In [250]:
#very rough please simplify when you can. Prob cant if we have initial constants
class Body:
    def __init__(self, mass, pos, velo, accel, force):
        self.mass=mass
        self.pos=np.array(pos,dtype=float)
        self.velo=np.array(velo,dtype=float)
        self.accel=np.array(accel,dtype=float)
        self.force=np.array(force,dtype=float)
        
        self.history_pos = [self.pos.copy()]
        self.history_velo = [self.velo.copy()]
        self.history_accel = [self.accel.copy()]
        self.history_force = [self.force.copy()]

    def update_history(self):
        self.history_pos.append(self.pos.copy())
        self.history_velo.append(self.velo.copy())
        self.history_accel.append(self.accel.copy())
        self.history_force.append(self.force.copy())
    
    def get_gravitational_force_2bodies(self, other):
        r_vec = other.pos-self.pos
        dist = np.linalg.norm(r_vec)
        if dist > 1000000:
            return (np.zero(3))
        mag = (Gravitational_Constant*self.mass*other.mass)/(dist**2)
        return (mag)

    

In [251]:
def combining_2_vectors(vector1, vector2): #combines the force of b2 on b1 and b3 on b1 for a total g force acted on b1
    array_one = np.array(vector1)
    array_two = np.array(vector2)
    summed_array = array_one + array_two
    return (summed_array)

In [252]:
bodies = []
bodies.append(Body( 11111, [3, 6, 3], [2, 5, 3], [8, 0, 3], [2, 0, 1])) #mass and initial( pos velo accel force )
bodies.append(Body( 22222, [7, 2, 7], [3, 2, 5], [6, 2, 2], [2, 9, 7]))
bodies.append(Body( 33333, [3, 3, 3], [4, 4, 4], [5, 5, 5], [6, 6, 6]))

In [253]:
vector1=np.zeros(3) 
vector2=np.zeros(3)
comb_vector1=np.zeros(3)
comb_vector2=np.zeros(3)
comb_vector3=np.zeros(3)

while (time!=total_time):
    vector1=bodies[0].get_gravitational_force_2bodies(bodies[1])
    vector2=bodies[0].get_gravitational_force_2bodies(bodies[2])
    comb_vector1=combining_2_vectors(vector1,vector2)

    vector1=bodies[1].get_gravitational_force_2bodies(bodies[0])
    vector2=bodies[1].get_gravitational_force_2bodies(bodies[2])
    comb_vector2=combining_2_vectors(vector1,vector2)

    vector1=bodies[2].get_gravitational_force_2bodies(bodies[0])
    vector2=bodies[2].get_gravitational_force_2bodies(bodies[1])
    comb_vector3=combining_2_vectors(vector1,vector2)

    bodies[0].force=combining_2_vectors(bodies[0].force,comb_vector1)
    bodies[1].force=combining_2_vectors(bodies[1].force,comb_vector2)
    bodies[2].force=combining_2_vectors(bodies[2].force,comb_vector3)
    for body in bodies:
        if body == bodies[0]:
            print(body.force)
        body.accel = body.force/body.mass
        body.velo += body.accel*dt
        body.pos += body.velo*dt
        body.update_history()
    time+=dt


[2.00308989 0.00308989 1.00308989]
[2.00441688 0.00441688 1.00441688]
[2.00504865 0.00504865 1.00504865]
[2.00540569 0.00540569 1.00540569]
[2.00563286 0.00563286 1.00563286]


In [254]:
# time=0
# while (time!=total_time):
#     for body in bodies: #should add forces to each body from the others
#         for body_other in bodies:
#             if(body != body_other):
#                 body.get_gravitational_force_2bodies(body_other)
#     for body in bodies: #should update accel, velo, pos of each body based on the total force
#         body.accel = body.force/body.mass
#         body.velo += body.accel*dt
#         body.pos += body.velo*dt
#         body.update_history()
#     time+=dt

In [255]:
#using this as a dumpster
# bodies[0].add_accel=combining_g_force(bodies[0].current_accel, updating_accel)  #using combine as just a vector combine atp, pls change name if possible, idk what to name it
# bodies[0].add_velocity=combining_g_force(bodies[0].current_velo, bodies[0].current_accel*dt)
# bodies[0].add_position=combining_g_force(bodies[0].current_pos, bodies[0].current_velo*dt)