In [287]:
#imports
import sys
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from mpl_toolkits.mplot3d import Axes3D


In [288]:
# Constants
Gravitational_Constant=6.6743*(10**-11)
dt=1.0
total_time=20
time=0.0

In [ ]:
#very rough please simplify when you can. Prob cant if we have initial constants
class Body:
    def __init__(self, mass, pos, velo, accel, force):
        self.mass=mass
        self.pos=np.array(pos,dtype=float)
        self.velo=np.array(velo,dtype=float)
        self.accel=np.array(accel,dtype=float)
        self.force=np.array(force,dtype=float)
        
        self.history_pos = [self.pos.copy()]
        self.history_velo = [self.velo.copy()]
        self.history_accel = [self.accel.copy()]
        self.history_force = [self.force.copy()]

    def update_history(self):
        self.history_pos.append(self.pos.copy())
        self.history_velo.append(self.velo.copy())
        self.history_accel.append(self.accel.copy())
        self.history_force.append(self.force.copy())
    
    def get_gravitational_force_2bodies(self, other):
        r_vec = other.pos-self.pos
        dist = np.linalg.norm(r_vec)
        if dist > 1000000:
            zeros=[0,0,0]
            returnzero=np.array(zeros)
            return (returnzero)
        mag = (Gravitational_Constant*self.mass*other.mass)/(dist**2)
        return (mag)

    

In [290]:
def combining_2_vectors(vector1, vector2): #combines the force of b2 on b1 and b3 on b1 for a total g force acted on b1
    array_one = np.array(vector1)
    array_two = np.array(vector2)
    summed_array = array_one + array_two
    return (summed_array)

In [291]:
bodies = []
bodies.append(Body( 1, [10003, 6, 3], [2, 5, 3], [8, 0, 3], [10000000, 0, 1])) #mass and initial( pos velo accel force )
bodies.append(Body( 2, [7, 2, 7], [3, 2, 5], [6, 2, 2], [2, 9, 7]))
bodies.append(Body( 3, [3, 3, 3], [4, 4, 4], [5, 5, 5], [6, 6, 6]))

In [292]:
vector1=np.zeros(3) 
vector2=np.zeros(3)
comb_vector1=np.zeros(3)
comb_vector2=np.zeros(3)
comb_vector3=np.zeros(3)

while (time!=total_time):
    vector1=bodies[0].get_gravitational_force_2bodies(bodies[1])
    vector2=bodies[0].get_gravitational_force_2bodies(bodies[2])
    comb_vector1=combining_2_vectors(vector1,vector2)

    vector1=bodies[1].get_gravitational_force_2bodies(bodies[0])
    vector2=bodies[1].get_gravitational_force_2bodies(bodies[2])
    comb_vector2=combining_2_vectors(vector1,vector2)

    vector1=bodies[2].get_gravitational_force_2bodies(bodies[0])
    vector2=bodies[2].get_gravitational_force_2bodies(bodies[1])
    comb_vector3=combining_2_vectors(vector1,vector2)

    bodies[0].force=combining_2_vectors(bodies[0].force,comb_vector1)
    bodies[1].force=combining_2_vectors(bodies[1].force,comb_vector2)
    bodies[2].force=combining_2_vectors(bodies[2].force,comb_vector3)
    for body in bodies:
        if body == bodies[0]:
            print(body.pos)
        body.accel = body.force/body.mass
        body.velo += body.accel*dt
        body.pos += body.velo*dt
        body.update_history()
    time+=dt


[1.0003e+04 6.0000e+00 3.0000e+00]
[1.0010005e+07 1.1000000e+01 7.0000000e+00]
[3.0010007e+07 1.6000000e+01 1.2000000e+01]
[6.0010009e+07 2.1000000e+01 1.8000000e+01]
[1.00010011e+08 2.60000000e+01 2.50000000e+01]
[1.50010013e+08 3.10000000e+01 3.30000000e+01]
[2.10010015e+08 3.60000000e+01 4.20000000e+01]
[2.80010017e+08 4.10000000e+01 5.20000000e+01]
[3.60010019e+08 4.60000000e+01 6.30000000e+01]
[4.50010021e+08 5.10000000e+01 7.50000000e+01]
[5.50010023e+08 5.60000000e+01 8.80000000e+01]
[6.60010025e+08 6.10000000e+01 1.02000000e+02]
[7.80010027e+08 6.60000000e+01 1.17000000e+02]
[9.10010029e+08 7.10000000e+01 1.33000000e+02]
[1.05001003e+09 7.60000000e+01 1.50000000e+02]
[1.20001003e+09 8.10000000e+01 1.68000000e+02]
[1.36001004e+09 8.60000000e+01 1.87000000e+02]
[1.53001004e+09 9.10000000e+01 2.07000000e+02]
[1.71001004e+09 9.60000000e+01 2.28000000e+02]
[1.90001004e+09 1.01000000e+02 2.50000000e+02]
